### ISSUE TITLE
ICS-Feeds für Klassenkalender können nicht abgerufen werden

### ISSUE THREAD

**Issue by pprs-it** [schuleintern/Webportal#281]
Beim Aufrufen der URLs für den ICS-Feed eines Klassenkalenders (bspw. `https://example.com/index.php?page=geticsfeed&a=1&b=<key>&c=<key>&d=q1w2/feed.ics`) wird die folgende PHP-Fehlermeldung angezeigt:

> **!!!Non-static method ICSFeed::getByIDAndKeys() cannot be called statically** in Line 13 in \<webroot>/framework/lib/page/kalender/geticsfeed.class.php
> 
> ```
> #0 <webroot>/framework/lib/system/requesthandler.class.php(325): geticsfeed->execute()
> #1 <webroot>/www/index.php(78): requesthandler->__construct('geticsfeed', Array)
> #2 {main}
> ```
> 
> [Schule-intern.de](https://www.schule-intern.de/) - **Version** 1.7.0

Diese Fehlermeldung scheint dadurch verursacht zu werden, dass in der Klasse ICSFeed vergessen wurde, die Methode `getByIDAndKeys` als `static` zu markieren (siehe Codeausschnitt).

https://github.com/schuleintern/Webportal/blob/88bf0f0468a72dd1bf0eedb84940b1c8a8df88b3/Upload/framework/lib/data/termine/ICSFeed.class.php#L98-L104

Mithilfe des folgenden Patches kann dieser Fehler zumindest behoben werden:

```diff
diff --git a/Upload/framework/lib/data/termine/ICSFeed.class.php b/Upload/framework/lib/data/termine/ICSFeed.class.php
index a3b033dd..c81742f4 100644
--- a/Upload/framework/lib/data/termine/ICSFeed.class.php
+++ b/Upload/framework/lib/data/termine/ICSFeed.class.php
@@ -95,7 +95,7 @@ class ICSFeed {

     }

-    public function getByIDAndKeys($id, $key1, $key2) {
+    public static function getByIDAndKeys($id, $key1, $key2) {
         $feed = DB::getDB()->query_first("SELECT * FROM icsfeeds WHERE feedID='" . intval($id). "' AND feedKey='" . DB::getDB()->escapeString($key1) . "' AND feedKey2='" . DB::getDB()->escapeString($key2) . "'");

```

Dann fällt allerdings auf, dass die gleiche URL nur noch eine leere Seite ergibt. Nach etwas Herumsuchen lässt sich auch hier die Ursache feststellen: Die Klasse `\Eluceo\iCal\Component\Calendar`, welche [in `geticsfeed` verwendet](
https://github.com/schuleintern/Webportal/blob/88bf0f0468a72dd1bf0eedb84940b1c8a8df88b3/Upload/framework/lib/page/kalender/geticsfeed.class.php#L272) und in [`framework/lib/ical/lib/Component/Calendar.php`](https://github.com/schuleintern/Webportal/blob/88bf0f0468a72dd1bf0eedb84940b1c8a8df88b3/Upload/framework/lib/ical/lib/Component/Calendar.php) definiert wird, kann vom Autolader nicht gefunden werden. Da ich mich mit den Details des Projekts und insbesondere den Abhängigkeiten nicht auskenne, kann ich hier auch keinen Lösungsvorschlag geben.

Noch als Hinweis nebenbei: Beim Abgleich der Datei `schuleinternautoloader.php` scheint es so, als wäre auf unserem System bereits die Folgeversion (1.7.0) installiert (vgl. [chrisland/SchuleIntern-Webportal](https://github.com/chrisland/SchuleIntern-Webportal/blob/92fd75a449fd224f3a700d2c9a7ca8f3e7e2db29/Upload/framework/lib/system/schuleinternautoloader.php)). Von dem, was ich den Unterschieden entnehmen kann, sollte das aber für dieses Verhalten keinen Unterschied machen.

---

Sollte dafür Bedarf bestehen, bin ich auch gerne per E-Mail oder Foren-Nachricht erreichbar.

**Comment by pprs-it** [comment]
Laut der Commit-Nachricht von 660fcee sollte das Verhalten wohl behoben sein, allerdings kann ich das (zumindest auf unserem System) nicht bestätigen. Dieses verwendet—laut Footer—Version 1.7.4, und wurde heute Nacht aktualisiert.

Nach einem flüchtigen Blick auf den genannten Commit ist mir aufgefallen, dass zwar am Anfang der Datei einige Klassen aus dem Namespace `\Eluceo\iCal\Domain\Entity` importiert werden, aber der Rest der Klasse weiterhin die fehlende Klasse `\Eluceo\iCal\Components\Calendar` verwendet. Da die "neue" Klasse anscheinend andere Werte für den Konstruktor erwartet, müssen hier aber mehr Anpassungen gemacht werden, als nur den Klassennamen auszutauschen.

Vielleicht schaffe ich es, das ganze geradezubiegen.
